version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/mini_erp
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_erp
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
